services:
  prefect_server:
    image: prefecthq/prefect:3.2.1-python3.11
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    volumes:
      - ./prefect:/root/.prefect
    networks:
      - mlflow-net

  prefect_orchestrator:
    image: philippedpz/epilepsy-prefect_orchestrator:latest
    depends_on:
      - prefect_server
    command: python /app/services/prefect_orchestrator/run_flows.py  # Changed this path
    volumes:
      - ./:/app       
      - ./data:/app/data
      - ./mlruns:/mlflow/mlruns
    environment:
      - PREFECT_API_URL=http://prefect_server:4200/api
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_ACCESS_KEY_ID=b0f89c64dcade7ba789272dd8e223d77fbbd1aa0
      - AWS_SECRET_ACCESS_KEY=b0f89c64dcade7ba789272dd8e223d77fbbd1aa0
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - mlflow-net

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns  
    working_dir: /mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlruns/mlflow.db
      --default-artifact-root /mlflow/mlruns
    networks:
      - mlflow-net

  patient_data_pull:
    image: philippedpz/epilepsy-patient_data_pull:latest
    volumes:
      - ./data/patients:/app/data/patients
      - ./data/patients_inference:/app/data/patients_inference

  auth_api:
    image: philippedpz/epilepsy-authentication:latest
    ports:
      - "8000:8000"
    networks:
      - mlflow-net
      - monitoring-net
    environment:
      - SECRET_KEY=your_secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  inference_api:
    image: philippedpz/epilepsy-inference:latest
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./production:/app/production
      - ./mlruns:/mlflow/mlruns
    networks:
      - mlflow-net
      - monitoring-net
    environment:
      - DATA_PATH=/app/data
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_PATH=/app/production/model/data/model.keras
      - SECRET_KEY=your_secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net
    depends_on:
      - auth_api
      - inference_api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3002"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring-net
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=3002

networks:
  mlflow-net:
    driver: bridge
  monitoring-net:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: